[package]
name = "binfmt"
version = "0.1.0"
authors = ["Connor Horman <chorman64@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0"
aligned = "0.3.4"

[lib]
name = "binfmt"
path = "lib.rs"

[features]
aout = []
coff = []
elf = []
macho = []
pe = []
llir = []
xir = []
ar = []
xo65 = []
default-formats = ["coff","elf","macho","pe","llir","xir","ar"]
default = ["default-formats"]
all-formats = ["default-formats","aout","xo65"]
all = ["all-formats"]