[package]
name = "binfmt"
version = "0.1.0"
authors = ["Connor Horman <chorman64@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0"
aligned = "0.3.4"
bytemuck = {version="1.5.1",features=["derive"]}
lazy_static = "1.4.0"
target-tuples = "0.2.2"

[lib]
name = "binfmt"

[features]
aout = []
coff = []
elf = []
macho = []
pe = ["coff"]
llir = []
xir = []
ar = []
xo65 = []
o65 = []
default-formats = ["coff","elf","macho","pe","llir","xir","ar"]
default = ["default-formats"]
all-formats = ["default-formats","aout","xo65","o65"]
all = ["all-formats"]